---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test-Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login 
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test
        run: docker-compose run --rm  app sh -c "python manage.py test"
      - name: Linting
        run: docker-compose run --rm app sh -c "flake8"

